#+ summary: Returns a graph containing the number of triples for a specified graph
#+ tags:
#+   - statistics

PREFIX void: <http://rdfs.org/ns/void#>

CONSTRUCT {
  ?_graph_iri a void:Dataset ;
    void:triples ?triples .
} 
WHERE
{
    GRAPH ?_graph_iri {
        SELECT (COUNT(*) AS ?triples) 
        { 
            ?s ?p ?o  
        } 
    }
}