#+ summary: Gets the number of triples for a VOID Dataset description
#+ tags:
#+   - statistics

PREFIX void: <http://rdfs.org/ns/void#>

SELECT ?triples
{
    ?_graph_iri a void:Dataset ;
     void:triples ?triples .
}